stages:
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./.service.yml
  - applyYamlConfig:
      path: ./.deployment.yml
notification:
  recipients:
  - recipient: builds
    notifier: c-qgf2m:n-fldgj
  condition:
  - Success
  - Failed
