apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: html-scraper
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-apps-html-scraper
  sessionAffinity: None
  type: ClusterIP
