if: tag IS blank
language: node_js
node_js:
- 12
env:
  matrix:
  - VERSION_PREFIX=1.0
services:
- docker
script:
- export FULL_VERSION=$VERSION_PREFIX.$TRAVIS_BUILD_NUMBER
- export REPO_TAGGED=$TRAVIS_REPO_SLUG:$FULL_VERSION
- export REPO_LATEST=$TRAVIS_REPO_SLUG:latest
- echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t $REPO_TAGGED .
- docker tag $REPO_TAGGED $REPO_LATEST
- docker push $REPO_TAGGED
- docker push $REPO_LATEST
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git remote add tagorigin https://$GH_USERNAME:$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git
- git tag $FULL_VERSION -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push tagorigin --tags
