apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: html-scraper
  labels:
    workload.user.cattle.io/workloadselector: deployment-apps-html-scraper
spec:
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-apps-html-scraper
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-apps-html-scraper
    spec:
      containers:
      - name: html-scraper
        image: thetablestop/html-scraper
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: Production
        - name: NODE_PORT
          value: "8080"
        - name: HEADLESS
          value: true
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
        volumeMounts:
        - mountPath: /mnt/nodeshared
          name: nodeshared
      volumes:
      - hostPath:
          path: /mnt/host
          type: DirectoryOrCreate
        name: nodeshared
